language: node_js
node_js:
  - 'node'
services:
  - postgresql
cache: yarn
before_script:
  - createdb cadence
  - psql -c "create user \"cadence-team\" with password 'cadence-rocks!';" -U postgres -d cadence
  - npx knex migrate:latest --env development
  - npx knex seed:run --env development
script:
  - yarn test:once --forceExit
  - cd client
  - yarn install
  - yarn test
